apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-08-25T16:10:54Z"
  generation: 1
  labels:
    app: default-deployment
  name: default-deployment
  namespace: default
  resourceVersion: "3339"
  uid: 1a8323ac-d6ad-4246-a90e-cdcff607976f
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: default-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: default-deployment
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
